server.port=8081
spring.application.name=enrollment-service

spring.datasource.url=${ENROLLMENT_DB_URL}
spring.datasource.username=${ENROLLMENT_DB_USER}
spring.datasource.password=${ENROLLMENT_DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true