version: '3.8'

services:
  # Database cho Course Service
  course-db:
    image: postgres:14
    container_name: course-db
    ports:
      - "5433:5432" # Map ra port 5433 để tránh trùng nếu máy bạn có Postgres sẵn
    environment:
      POSTGRES_DB: course_db
      POSTGRES_USER: ${COURSE_DB_USER}
      POSTGRES_PASSWORD: ${COURSE_DB_PASSWORD}
    volumes:
      - course_db_data:/var/lib/postgresql/data

  # Database cho Enrollment Service
  enrollment-db:
    image: postgres:14
    container_name: enrollment-db
    ports:
      - "5434:5432" # Map ra port 5434
    environment:
      POSTGRES_DB: enrollment_db
      POSTGRES_USER: ${ENROLLMENT_DB_USER}
      POSTGRES_PASSWORD: ${ENROLLMENT_DB_PASSWORD}
    volumes:
      - enrollment_db_data:/var/lib/postgresql/data

  # eureka server
  eureka-server:
    build: ./eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"

  # api gateway
  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    depends_on:
      - eureka-server
      - zipkin
    env_file:
      - ./api-gateway/.env.prod
    ports:
      - "8080:8080"

  # course service
  course-service:
    build: ./course-service
#    container_name: course-service
    depends_on:
      - course-db
      - enrollment-db
      - eureka-server
      - zipkin
      - api-gateway
#    ports:
#      - "8081:8081"
    env_file:
      - ./course-service/.env.prod


  # enrollment service
  enrollment-service:
    build: ./enrollment-service
    container_name: enrollment-service
    depends_on:
      - course-db
      - enrollment-db
      - zipkin
      - api-gateway
      - eureka-server
    ports:
      - "8082:8082"
    env_file:
      - ./enrollment-service/.env.prod




  # zipkin
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"

volumes:
  course_db_data:
  enrollment_db_data: