server.port=0
spring.application.name=course-service

spring.datasource.url=${COURSE_DB_URL}
spring.datasource.username=${COURSE_DB_USER}
spring.datasource.password=${COURSE_DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# eureka config
eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL:http://localhost:8761/eureka}
eureka.instance.preferIpAddress=true