server.port=8082
spring.application.name=course-service

spring.datasource.url=${COURSE_DB_URL}
spring.datasource.username=${COURSE_DB_USER}
spring.datasource.password=${COURSE_DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true